Update workflows

diff --git a/.github/workflows/internal-release.yml b/.github/workflows/internal-release.yml
--- a/.github/workflows/internal-release.yml
+++ b/.github/workflows/internal-release.yml
@@ -1,9 +1,16 @@
-name: Release
+name: Internal Release
 
 on:
-  release:
-    types:
-      - published
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: Release Tag (with Build Number)
+        default: v1.0.0+1
+        required: true
+      body:
+        description: Release Notes
+        default: No release notes provided
+        required: true
 
 env:
   # Version Information
@@ -13,15 +20,13 @@ env:
   RUBY_VERSION: 3.3
 
   # Build Information
-  RELEASE_NOTES: ${{ github.event.release.body }}
-  TAG_NAME: ${{ github.event.release.tag_name }}
+  RELEASE_NOTES: ${{ github.event.inputs.body }}
+  TAG_NAME: ${{ github.event.inputs.tag }}
 
 jobs:
   prebuild:
     name: Prebuild
     runs-on: ubuntu-latest
-
-    if: ${{ github.event_name == 'release' && github.ref == 'refs/heads/main' }}
 
     # Build name and number to pass to Flutter commands.
     outputs:
@@ -41,6 +46,18 @@ jobs:
         run: |
           echo "Invalid Release Tag: \"$TAG_NAME\"...Failing Workflow"
           exit 1
+
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-tags: true
+
+      - name: Verify Version Tag Exists
+        id: verify-tag-exists
+        run: |
+          git fetch --depth=1 origin +refs/tags/${TAG_NAME}
+          git tag --list | grep -q ${TAG_NAME} || (echo "Tag not found: ${TAG_NAME}" && exit 1)
 
       - name: Split Tag
         id: split-tag
@@ -66,8 +83,8 @@ jobs:
       run:
         working-directory: ${{ github.workspace }}/android
 
-    # Use 'production' secrets for release events.
-    environment: production
+    # Use 'staging' secrets for internal releases.
+    environment: staging
 
     env:
       # Android Information
@@ -77,7 +94,7 @@ jobs:
       ANDROID_SERVICE_ACCOUNT_JSON: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
       ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
       ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
-      SUPPLY_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
+      SUPPLY_PACKAGE_NAME: com.ncalteen.flutter_fastlane_demo
 
       # Build Information
       BUILD_NAME: ${{ needs.prebuild.outputs.build_name }}
@@ -112,7 +129,7 @@ jobs:
       - name: Build and Upload
         id: build-upload
         run: |
-          fastlane production
+          fastlane internal
 
   ios:
     name: Build and Deploy (iOS)
@@ -125,8 +142,8 @@ jobs:
       run:
         working-directory: ${{ github.workspace }}/ios
 
-    # Use 'production' secrets for release events.
-    environment: production
+    # Use 'staging' secrets for internal releases.
+    environment: staging
 
     # prettier-ignore
     env:
@@ -185,4 +202,4 @@ jobs:
       - name: Build and Upload
         id: build-upload
         run: |
-          fastlane production
+          fastlane internal
